spring.application.name=demo
spring.main.web-application-type=servlet
server.port=8080


# URL de connexion (ici sur le port par défaut 3306 et la base library_db)
spring.datasource.url=jdbc:mysql://localhost:3306/demo_springboot?useSSL=false&serverTimezone=UTC
spring.datasource.username=demo_springboot
spring.datasource.password=demo1234

# Pilote MySQL
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true